/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_Chronograph */

#ifndef _Included_utils_Chronograph
#define _Included_utils_Chronograph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_Chronograph
 * Method:    getCPUClock
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_utils_Chronograph_getCPUClock
  (JNIEnv *, jobject);

/*
 * Class:     utils_Chronograph
 * Method:    getElapsedTime
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_utils_Chronograph_getElapsedTime
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
