/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_TestCase */

#ifndef _Included_main_TestCase
#define _Included_main_TestCase
#ifdef __cplusplus
extern "C" {
#endif
#undef main_TestCase_FIVE_SECONDS
#define main_TestCase_FIVE_SECONDS 5000000L
/*
 * Class:     main_TestCase
 * Method:    testNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_TestCase_testNatives
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
