/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pthread_ThreadDispatcher */

#ifndef _Included_pthread_ThreadDispatcher
#define _Included_pthread_ThreadDispatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pthread_ThreadDispatcher
 * Method:    dispatch
 * Signature: (Lpthread/model/ThreadModel;)V
 */
JNIEXPORT void JNICALL Java_pthread_ThreadDispatcher_dispatch
  (JNIEnv *, jobject, jobject);

/*
 * Class:     pthread_ThreadDispatcher
 * Method:    finish
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pthread_ThreadDispatcher_finish
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
